export default {
  title: `Mick Patterson`,
  author: `Mick Patterson`,
  description: `Short snippets of frequent functions, 
    small tips and tricks I've found important and useful while building things, 
    along with some case studies of my projects and bits about me and my story`,
  siteUrl: `https://www.mickpatterson.com.au`,
  social: {
    twitter: `Mick_Patterson_`,
  },
  keywords: [
    `blog`,
    `angular`,
    `javascript`,
    `ionic`,
    `nodejs`,
    `sql`,
    `mongo`,
    `sql server`,
    `c#`,
    `fullstack`,
    `html`,
  ],
  image: "/blog-header-image.jpg",
}
